### ISSUE TITLE
Incorrect path separator within resulting zip file

### ISSUE THREAD

**Issue by nagyo** [IHTSDO/delta-generator-tool#1]
Hi,

Upon testing the tool, we have found and issue with how path separators are used in the resulting archive.

Generating a delta RF2 using Windows will register the individual file paths like this:

```
/SnomedCT_InternationalRF2_PRODUCTION_20211130T120000Z\Delta\Terminology\sct2_Concept_Delta_INT_20211130.txt
```

Whereas the official SNOMED CT release archive uses the standardized format:
```
/SnomedCT_InternationalRF2_PRODUCTION_20210731T120000Z/Delta/Terminology/sct2_Concept_Delta_INT_20210731.txt
```

This inconsistency most likely comes from using File.separator and ZipEntry, both being system dependant when it comes to path separators.

According to the [official ZIP file format specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT):

> 4.4.17.1 The name of the file, with optional relative path.
The path stored MUST NOT contain a drive or
device letter, or a leading slash.  All slashes
MUST be forward slashes '/' as opposed to
backwards slashes '\' for compatibility with Amiga
and UNIX file systems etc.  If input came from standard
input, there is no file name field.  

It might seem minor, but in case someone uses this tool to create a delta RF2 archive, which is then eventually fed into another tool expecting UNIX style zip entries, file processing could fail.

Some useful stackoverflow discussions:
- [Zip file is created with windows path separator](https://stackoverflow.com/questions/57248542/zip-file-is-created-with-windows-path-separator)
- [File separators of Path name of ZipEntry?](https://stackoverflow.com/questions/13846000/file-separators-of-path-name-of-zipentry)

Snippet to list path of zip entries:
```
public static void main(String[] args) throws IOException {
	try (FileSystem zipfs = FileSystems.newFileSystem(Paths.get("C:\\path\\to\\SnomedCT_InternationalRF2_PRODUCTION_20210731T120000Z.zip"), null)) {
		for (final Path path : zipfs.getRootDirectories()) {
			Files.walkFileTree(path, new SimpleFileVisitor<Path>() {
				@Override 
				public FileVisitResult visitFile(final Path path, final BasicFileAttributes attrs) throws IOException {
					System.out.println(path.toAbsolutePath().toString());
					return FileVisitResult.CONTINUE;
				}
			});
		}
	}
}
```

Regards,

Gábor

**Comment by pgwilliams** [comment]
Yes great spotting thanks Gábor.   We'd previously discussed the need to test these zip archive creators in a Windows environment which I did, but didn't try loading the results into Snowstorm which I think would have failed.   I will standardise the path separators as you suggest.

**Comment by pgwilliams** [comment]
Thanks again @nagyo.   This issue has now been addressed in https://github.com/IHTSDO/delta-generator-tool/releases/tag/1.1.0
